spring:
  datasource:
    url: jdbc:mysql:/db
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      encoding: UTF-8
      separator: ;
      username: root
      password: root
      #这两个脚本文件放在resources/db/db.sql
      schema-locations: classpath*:db/tag-tag-schema.sql
      data-locations: classpath*:db/tag-data.sql
      mode: always

  main:
    banner-mode: console


mybatis-plus:
  global-config:
    banner: off


logging:
  level:
    root: off


